name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: copile libft
        run: make copile

      - name: run mytest
        run: make mytest

      - name: run test with war-machine (external tests)
        run: make war-machine
